namespace PAXAnalyticsAPI.Models
{
    public class DayModel
    {
        public DateOnly Day { get; set; }
        public int PaxArriving00 { get; set; }
        public int PaxArriving01 { get; set; }
        public int PaxArriving02 { get; set; }
        public int PaxArriving03 { get; set; }
        public int PaxArriving04 { get; set; }
        public int PaxArriving05 { get; set; }
        public int PaxArriving06 { get; set; }
        public int PaxArriving07 { get; set; }
        public int PaxArriving08 { get; set; }
        public int PaxArriving09 { get; set; }
        public int PaxArriving10 { get; set; }
        public int PaxArriving11 { get; set; }
        public int PaxArriving12 { get; set; }
        public int PaxArriving13 { get; set; }
        public int PaxArriving14 { get; set; }
        public int PaxArriving15 { get; set; }
        public int PaxArriving16 { get; set; }
        public int PaxArriving17 { get; set; }
        public int PaxArriving18 { get; set; }
        public int PaxArriving19 { get; set; }
        public int PaxArriving20 { get; set; }
        public int PaxArriving21 { get; set; }
        public int PaxArriving22 { get; set; }
        public int PaxArriving23 { get; set; }
        public int PlanesArriving00 { get; set; }
        public int PlanesArriving01 { get; set; }
        public int PlanesArriving02 { get; set; }
        public int PlanesArriving03 { get; set; }
        public int PlanesArriving04 { get; set; }
        public int PlanesArriving05 { get; set; }
        public int PlanesArriving06 { get; set; }
        public int PlanesArriving07 { get; set; }
        public int PlanesArriving08 { get; set; }
        public int PlanesArriving09 { get; set; }
        public int PlanesArriving10 { get; set; }
        public int PlanesArriving11 { get; set; }
        public int PlanesArriving12 { get; set; }
        public int PlanesArriving13 { get; set; }
        public int PlanesArriving14 { get; set; }
        public int PlanesArriving15 { get; set; }
        public int PlanesArriving16 { get; set; }
        public int PlanesArriving17 { get; set; }
        public int PlanesArriving18 { get; set; }
        public int PlanesArriving19 { get; set; }
        public int PlanesArriving20 { get; set; }
        public int PlanesArriving21 { get; set; }
        public int PlanesArriving22 { get; set; }
        public int PlanesArriving23 { get; set; }
        public int PaxDeparting00 { get; set; }
        public int PaxDeparting01 { get; set; }
        public int PaxDeparting02 { get; set; }
        public int PaxDeparting03 { get; set; }
        public int PaxDeparting04 { get; set; }
        public int PaxDeparting05 { get; set; }
        public int PaxDeparting06 { get; set; }
        public int PaxDeparting07 { get; set; }
        public int PaxDeparting08 { get; set; }
        public int PaxDeparting09 { get; set; }
        public int PaxDeparting10 { get; set; }
        public int PaxDeparting11 { get; set; }
        public int PaxDeparting12 { get; set; }
        public int PaxDeparting13 { get; set; }
        public int PaxDeparting14 { get; set; }
        public int PaxDeparting15 { get; set; }
        public int PaxDeparting16 { get; set; }
        public int PaxDeparting17 { get; set; }
        public int PaxDeparting18 { get; set; }
        public int PaxDeparting19 { get; set; }
        public int PaxDeparting20 { get; set; }
        public int PaxDeparting21 { get; set; }
        public int PaxDeparting22 { get; set; }
        public int PaxDeparting23 { get; set; }
        public int PlanesDeparting00 { get; set; }
        public int PlanesDeparting01 { get; set; }
        public int PlanesDeparting02 { get; set; }
        public int PlanesDeparting03 { get; set; }
        public int PlanesDeparting04 { get; set; }
        public int PlanesDeparting05 { get; set; }
        public int PlanesDeparting06 { get; set; }
        public int PlanesDeparting07 { get; set; }
        public int PlanesDeparting08 { get; set; }
        public int PlanesDeparting09 { get; set; }
        public int PlanesDeparting10 { get; set; }
        public int PlanesDeparting11 { get; set; }
        public int PlanesDeparting12 { get; set; }
        public int PlanesDeparting13 { get; set; }
        public int PlanesDeparting14 { get; set; }
        public int PlanesDeparting15 { get; set; }
        public int PlanesDeparting16 { get; set; }
        public int PlanesDeparting17 { get; set; }
        public int PlanesDeparting18 { get; set; }
        public int PlanesDeparting19 { get; set; }
        public int PlanesDeparting20 { get; set; }
        public int PlanesDeparting21 { get; set; }
        public int PlanesDeparting22 { get; set; }
        public int PlanesDeparting23 { get; set; }
    }
}
